DROP TABLE USERDATA CASCADE CONSTRAINTS;
DROP TABLE USERCONTENT;
DROP TABLE USERFOLLOW;
DROP SEQUENCE USERNOSQ;
DROP SEQUENCE GROUPNOSQ;
DROP SEQUENCE BOARDNOSQ;

CREATE SEQUENCE USERNOSQ NOCACHE;

CREATE TABLE USERDATA(
	USERNO NUMBER NOT NULL,
	USERID VARCHAR2(500) NOT NULL,
	USERPW VARCHAR2(500) NOT NULL,
	USERNAME VARCHAR2(1000) NOT NULL,
	USERADDR VARCHAR2(4000) NOT NULL,
	USERPHONE VARCHAR2(4000) NOT NULL,
	USEREMAIL VARCHAR2(100) NOT NULL,
	USERENABLED VARCHAR2(2) NOT NULL,
	USERROLE VARCHAR2(50) NOT NULL,
	USERFOLLOW NUMBER NOT NULL,
	CONSTRAINT USERDATA_PK PRIMARY KEY(USERNO),
	CONSTRAINT USERDATA_UQ_ID UNIQUE(USERID),
	CONSTRAINT USERDATA_UQ_PHONE UNIQUE(USERPHONE),
	CONSTRAINT USERDATA_UQ_EMAIL UNIQUE(USEREMAIL),
	CONSTRAINT USERDATA_ENABLE_CHK CHECK(USERENABLED IN('Y','N'))
);

--글 번호 시퀀스(PRIMARY KEY)
CREATE SEQUENCE BOARDNOSQ NOCACHE;

--그룹 번호 시퀀스(새로운 글 등록 할 때만)
CREATE SEQUENCE GROUPNOSQ NOCACHE;

CREATE TABLE USERCONTENT(
	BOARDNO NUMBER NOT NULL,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLE VARCHAR2(2000) ,
	CONTENT VARCHAR2(4000),
	USERIDNO NUMBER NOT NULL, 
	USERIMGNAME VARCHAR2(50),
	USERLIKE NUMBER NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT USERCONTENT_PK PRIMARY KEY(BOARDNO),
	CONSTRAINT USERCONTENT_FK FOREIGN KEY(USERIDNO) REFERENCES USERDATA(USERNO)
);

CREATE TABLE USERFOLLOW(
   USERS VARCHAR2(500), 
   FOLLOWERUSER VARCHAR2(500),
   CONSTRAINT FOLLOW_PK PRIMARY KEY(USERS,FOLLOWERUSER),
   CONSTRAINT USERS_FK FOREIGN KEY(USERS) REFERENCES USERDATA(USERID),
   CONSTRAINT FOLLOWERUSER_FK FOREIGN KEY(FOLLOWERUSER) REFERENCES USERDATA(USERID)
);

SELECT * FROM USERCONTENT ORDER BY GROUPNO DESC, GROUPSQ;

SELECT * FROM USERDATA;
SELECT * FROM USERFOLLOW;


INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'admin', 'admin123', '관리자', '서울특별시', '010-1234-5678', 'admin1@gmail.com', 'Y', 
'ADMIN', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'manager', 'manager123', '매니저', '경기도', '010-9876-5432', 'manager1@gmail.com', 'Y', 
'MANAGER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'honggd', 'hong123', '홍길동', '충청북도', '010-5256-4810', 'honggd@gmail.com', 'Y', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'parksj', 'park123', '박성진', '부산광역시', '010-9319-0116', 'parksj@naver.com', 'Y', 
'USER', 0
);
INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'choisg', 'choisg123', '최슬기', '경상북도', '010-6752-4572', 'choisg@kakao.com', 'Y', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'boomj', 'boomj123', '부민준', '제주도', '010-9561-2568', 'boomj@nate.com', 'Y', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'seoja', 'seoja123', '서지애', '울산광역시', '010-8739-5374', 'seoja@hanmail.net', 'Y', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'kimdu', 'kimdu123', '김도운', '강원도', '010-2595-0825', 'kimdu@gmail.com', 'Y', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'handy', 'handy123', '한도연', '전라남도', '010-4649-1245', 'handy@naver.com', 'Y', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'leech', 'leech123', '이채현', '광주광역시', '010-1325-3585', 'leech@nate.com', 'N', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'choi3854', 'choi3854123', '최승민', '인천광역시', '010-8453-3854', 'choi3854@empal.com', 'Y', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'minyj', 'minyj123', '민예지', '경상남도', '010-9355-8975', 'minyj@korea.com', 'Y', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'kwonmj', 'kwonmj123', '권민준', '대전광역시', '010-1213-4557', 'kwonmj@nate.com', 'N', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'kimjw', 'kimjw123', '김재원', '전라북도', '010-7433-4656', 'kimjw@gmail.com', 'Y', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'parksu', 'parksu123', '박선우', '서울특별시', '010-6536-5641', 'parksu@empal.com', 'N', 
'USER', 0
);

INSERT INTO USERDATA VALUES(
USERNOSQ.NEXTVAL, 'leegu', 'leegu123', '이가은', '경상북도', '010-9894-2343', 'leegu@hanmail.net', 'Y', 
'USER', 0
);


